//
//  HistoryViewModel.swift
//  baseapp
//
//  Created Thanh Nguyên Trần on 13/04/2022.
//  Copyright © 2022 Avengers Mobile Team. All rights reserved.
//
//  Template generated by Avengers Mobile Team
//

import Foundation
import RealmSwift
import SwiftyAttributes
import Bond

//                        _oo0oo_
//                       o8888888o
//                       88" . "88
//                       (| -_- |)
//                       0\  =  /0
//                     ___/`---'\___
//                   .' \|     |// '.
//                  / \|||  :  |||// \
//                 / _||||| -:- |||||- \
//                |   | \\  -  /// |   |
//                | \_|  ''\---/''  |_/ |
//                \  .-\__  '-'  ___/-. /
//              ___'. .'  /--.--\  `. .'___
//           ."" '<  `.___\_<|>_/___.' >' "".
//          | | :  `- \`.;`\ _ /`;.`/ - ` : | |
//          \  \ `_.   \_ __\ /__ _/   .-` /  /
//      =====`-.____`.___ \_____/___.-`___.-'=====
//                        `=---='
// Đức phật nơi đây phù hộ code con chạy không Bug. Nam mô a di đà Phật
protocol HistoryLoadTableViewDelegate: class {
    func reloadTableView()
}
class HistoryViewModel: BaseViewModel{
    private let realm = try! Realm()
    var items = MutableObservableArray<String>.init([])
    
    private var historyArray: [PlantBugModel] = []
    var loadTableViewDelegate: HistoryLoadTableViewDelegate?

    
    var models: [HistoryModel] = [] {
        didSet {
            self.loadTableViewDelegate?.reloadTableView()
        }
    }
    
    func loadData() {
        historyArray.removeAll()
        self.loadTableViewDelegate?.reloadTableView()
        historyArray = DatabaseManager.shared.listHistoryImage()
        models = DatabaseManager.shared.listHistoryImage().sorted(by: {$0.date > $1.date}).map { m in
            let model = HistoryModel()
            model.id = m.id
            model.name = m.name
            model.image = m.image
            model.confidence = m.confidence
            model.date = m.date
            model.full_desc = m.myDescription
            model.wiki_link = m.wiki
            model.images = Array(m.gallery)
            return model
        }
        if historyArray.isEmpty == false {
            print("xxxx co du lieu trong model history")
            print(historyArray.count)
        }
        self.loadTableViewDelegate?.reloadTableView()
        
        
    }
    deinit {
        print("Deinit: " + String(describing: type(of: self)))
    }

}

extension HistoryViewModel: DataControllerDelegate {
    func saveDataBug() {
       
    }
    
    func saveData() {
        self.loadData()
    }

}
