//
//  HistoryController.swift
//  baseapp
//
//  Created Thanh Nguyên Trần on 13/04/2022.
//  Copyright © 2022 Avengers Mobile Team. All rights reserved.
//
//  Template generated by Avengers Mobile Team
//

import UIKit

//                        _oo0oo_
//                       o8888888o
//                       88" . "88
//                       (| -_- |)
//                       0\  =  /0
//                     ___/`---'\___
//                   .' \|     |// '.
//                  / \|||  :  |||// \
//                 / _||||| -:- |||||- \
//                |   | \\  -  /// |   |
//                | \_|  ''\---/''  |_/ |
//                \  .-\__  '-'  ___/-. /
//              ___'. .'  /--.--\  `. .'___
//           ."" '<  `.___\_<|>_/___.' >' "".
//          | | :  `- \`.;`\ _ /`;.`/ - ` : | |
//          \  \ `_.   \_ __\ /__ _/   .-` /  /
//      =====`-.____`.___ \_____/___.-`___.-'=====
//                        `=---='
// Đức phật nơi đây phù hộ code con chạy không Bug. Nam mô a di đà Phật

class HistoryController: BaseController<HistoryViewModel, HistoryNavigator> {


    // MARK: - Properties

   
    @IBOutlet weak var historyTableView: UITableView!
    var dataSource : HistoryDataSource = HistoryDataSource()
    
    // MARK: - Life Cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setTableView()
        self.navigationController?.navigationBar.isHidden = true
        self.navigationController?.navigationBar.isHidden = true
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        self.viewModel.loadData()
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

    }


    // MARK: - Binding UI
    override func bindUI() {
        super.bindUI()

    }

    //MARK: - Functions
    func doSomeThing() {

    }
    func setTableView() {
       self.historyTableView.separatorColor = UIColor.clear
        historyTableView.backgroundColor = UIColor.clear
        dataSource.registerCell(forTableView: historyTableView)
        viewModel.loadTableViewDelegate = self
        dataSource.historyDelegate = self
        historyTableView.emptyDataSetSource = dataSource
        historyTableView.emptyDataSetDelegate = dataSource
        dataSource.array = viewModel.models
        historyTableView.delegate = dataSource
        historyTableView.dataSource = dataSource
    }
    

}

// MARK: - Extension
extension HistoryController: HistoryLoadTableViewDelegate {
    func reloadTableView() {
        dataSource.array = viewModel.models
        historyTableView.reloadData()
    }
    
    
}
extension HistoryController: HistoryDataSourceDelegate{
   func loadHistoryDetail(itemModel: HistoryModel) {
    self.navigator?.navigate(to: .detailResult(itemModel: itemModel))
}
}
