//
//  CollectionViewModel.swift
//  baseapp
//
//  Created Thanh Nguyên Trần on 13/04/2022.
//  Copyright © 2022 Avengers Mobile Team. All rights reserved.
//
//  Template generated by Avengers Mobile Team
//

import Foundation
import UIKit
import SwiftyAttributes

//                        _oo0oo_
//                       o8888888o
//                       88" . "88
//                       (| -_- |)
//                       0\  =  /0
//                     ___/`---'\___
//                   .' \|     |// '.
//                  / \|||  :  |||// \
//                 / _||||| -:- |||||- \
//                |   | \\  -  /// |   |
//                | \_|  ''\---/''  |_/ |
//                \  .-\__  '-'  ___/-. /
//              ___'. .'  /--.--\  `. .'___
//           ."" '<  `.___\_<|>_/___.' >' "".
//          | | :  `- \`.;`\ _ /`;.`/ - ` : | |
//          \  \ `_.   \_ __\ /__ _/   .-` /  /
//      =====`-.____`.___ \_____/___.-`___.-'=====
//                        `=---='
// Đức phật nơi đây phù hộ code con chạy không Bug. Nam mô a di đà Phật



protocol CollectionLoadTableViewDelegate: class {
    func reloadTableView()
    func reloadBugTableView()
}

class CollectionViewModel: BaseViewModel {
    
    var models: [HistoryModel] = [] {
        didSet {
            self.loadTableViewDelegate?.reloadTableView()
        }
    }
    var modelsBug: [HistoryModel] = [] {
        didSet {
            self.loadTableViewDelegate?.reloadBugTableView()
        }
    }
    
    var collectionItem = [CollectionModel]()
    var bugData = [BugModel]()
    var loadTableViewDelegate: CollectionLoadTableViewDelegate?
    
    func loadData() {
        self.collectionItem.removeAll()
        self.loadTableViewDelegate?.reloadTableView()
        let arrs = DatabaseManager.shared.getCollectionImages()
        models = DatabaseManager.shared.getCollectionImages().map({ m in
            let model = HistoryModel()
            model.id = m.id
            model.name = m.name
            model.image = m.image
            model.confidence = m.confidence
            model.commonName = m.commonname
            model.date = m.date
            model.full_desc = m.myDescription
            model.wiki_link = m.wiki
            model.images = Array(m.gallery)
            return model
        })
        print("TTN plant")
        self.collectionItem = arrs
        self.loadTableViewDelegate?.reloadTableView()
    }
    
    func loadDataBug(){
        self.bugData.removeAll()
        self.loadTableViewDelegate?.reloadBugTableView()
        let arrs = DatabaseManager.shared.getBugImages()
        modelsBug = DatabaseManager.shared.getBugImages().map({ m in
            let model = HistoryModel()
            model.id = m.id
            model.name = m.name
            model.image = m.image
            model.confidence = m.confidence
            model.date = m.date
            model.full_desc = m.myDescription
            model.wiki_link = m.wiki
            model.images = Array(m.gallery)
            return model
        })
        print("TTN bug")
        self.bugData = arrs
        self.loadTableViewDelegate?.reloadBugTableView()
    }
}


extension CollectionViewModel: DataControllerDelegate {
    func saveData() {
        self.loadData()
    }
    func saveDataBug() {
        self.loadDataBug()
    }
   
}
