//
//  Onboarding3Controller.swift
//  baseapp
//
//  Created Thanh Nguyên Trần on 14/04/2022.
//  Copyright © 2022 Avengers Mobile Team. All rights reserved.
//
//  Template generated by Avengers Mobile Team
//

import UIKit

//                        _oo0oo_
//                       o8888888o
//                       88" . "88
//                       (| -_- |)
//                       0\  =  /0
//                     ___/`---'\___
//                   .' \|     |// '.
//                  / \|||  :  |||// \
//                 / _||||| -:- |||||- \
//                |   | \\  -  /// |   |
//                | \_|  ''\---/''  |_/ |
//                \  .-\__  '-'  ___/-. /
//              ___'. .'  /--.--\  `. .'___
//           ."" '<  `.___\_<|>_/___.' >' "".
//          | | :  `- \`.;`\ _ /`;.`/ - ` : | |
//          \  \ `_.   \_ __\ /__ _/   .-` /  /
//      =====`-.____`.___ \_____/___.-`___.-'=====
//                        `=---='
// Đức phật nơi đây phù hộ code con chạy không Bug. Nam mô a di đà Phật

class Onboarding3Controller: UIViewController {

    @IBOutlet weak var continueButton: UIButton!

    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationController?.isNavigationBarHidden = true
        continueButton.reactive.tap
            .observeNext { [weak self] in
                guard let strongSelf = self else { return }
                strongSelf.openController()
            }.dispose(in: bag)
        setupLayout()
    }

    func openController() {
        let viewModel = PremiumViewModel()
        let navigator = PremiumNavigator()
        let controller = PremiumController(viewModel: viewModel, navigator: navigator)
        controller.modalPresentationStyle = .fullScreen
        self.navigationController?.present(controller, animated: true, completion: nil)

    }
    func setupLayout(){
        continueButton.layer.cornerRadius = 26.5
        continueButton.backgroundColor = UIColor.init(hexString: "00B485")
    }

}
