//
//  HomeController.swift
//  baseapp
//
//  Created Thanh Nguyên Trần on 13/04/2022.
//  Copyright © 2022 Avengers Mobile Team. All rights reserved.
//
//  Template generated by Avengers Mobile Team
//

import UIKit
import ChameleonFramework
//                        _oo0oo_
//                       o8888888o
//                       88" . "88
//                       (| -_- |)
//                       0\  =  /0
//                     ___/`---'\___
//                   .' \|     |// '.
//                  / \|||  :  |||// \
//                 / _||||| -:- |||||- \
//                |   | \\  -  /// |   |
//                | \_|  ''\---/''  |_/ |
//                \  .-\__  '-'  ___/-. /
//              ___'. .'  /--.--\  `. .'___
//           ."" '<  `.___\_<|>_/___.' >' "".
//          | | :  `- \`.;`\ _ /`;.`/ - ` : | |
//          \  \ `_.   \_ __\ /__ _/   .-` /  /
//      =====`-.____`.___ \_____/___.-`___.-'=====
//                        `=---='
// Đức phật nơi đây phù hộ code con chạy không Bug. Nam mô a di đà Phật

class HomeController: BaseController<HomeViewModel, HomeNavigator> {


    // MARK: - Properties

    @IBOutlet weak var plantView: UIView!
    @IBOutlet weak var bugView: UIView!

    @IBOutlet weak var plantBug: UIButton!
    @IBOutlet weak var bugBtn: UIButton!
    // MARK: - Life Cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupLayout()
        navigationController?.isNavigationBarHidden = true
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        tabBarController?.tabBar.isHidden = false

    }


    // MARK: - Binding UI
    override func bindUI() {
        super.bindUI()
        plantBug.reactive.tap.observeNext { [weak self] in
            guard let strongSelf = self else {return}
            strongSelf.navigator?.navigate(to: .camera(type: .plant))
        }
        bugBtn.reactive.tap.observeNext { [weak self] in
            guard let strongSelf = self else {return}
            strongSelf.navigator?.navigate(to: .camera(type: .bug))
        }
        
    }

    //MARK: - Functions
    func doSomeThing() {

    }
    func setupLayout(){
        plantView.backgroundColor = UIColor.init(hexString: "D6DDD6")
        bugView.backgroundColor = UIColor.init(hexString: "E9E8E6")
        
        bugView.roundBottomRightTopLeft(radius: 25)
        plantView.roundBottomleftTopRight(radius: 25)
       
        
    }
    func showPremium() {
        navigator?.navigate(to: .premium)
    }
    
    

}

// MARK: - Extension

