//
//  MoreResultNavigator.swift
//  baseapp
//
//  Created Thanh Nguyên Trần on 20/04/2022.
//  Copyright © 2022 Avengers Mobile Team. All rights reserved.
//
//  Template generated by Avengers Mobile Team
//

import Foundation

//                        _oo0oo_
//                       o8888888o
//                       88" . "88
//                       (| -_- |)
//                       0\  =  /0
//                     ___/`---'\___
//                   .' \|     |// '.
//                  / \|||  :  |||// \
//                 / _||||| -:- |||||- \
//                |   | \\  -  /// |   |
//                | \_|  ''\---/''  |_/ |
//                \  .-\__  '-'  ___/-. /
//              ___'. .'  /--.--\  `. .'___
//           ."" '<  `.___\_<|>_/___.' >' "".
//          | | :  `- \`.;`\ _ /`;.`/ - ` : | |
//          \  \ `_.   \_ __\ /__ _/   .-` /  /
//      =====`-.____`.___ \_____/___.-`___.-'=====
//                        `=---='
// Đức phật nơi đây phù hộ code con chạy không Bug. Nam mô a di đà Phật

enum MoreResultRouter: RouterType {
    case results(itemModelArray : [ItemModel], identifyType: HomeItemType, index: Int, userImage: UIImage)
}

class MoreResultNavigator: BaseNavigator<MoreResultRouter> {
    override func navigate(to:MoreResultRouter) {
        switch to {
        case .results(let itemModelArray, let identifyType, let index, let image):
            let vm = ResultViewModel()
            vm.itemIdentifyType = identifyType
            vm.results = itemModelArray
            vm.loadResultsModel(atIndex: index)
            vm.isLoadFromMoreResults = true
            vm.userImage = image
            let nav = ResultNavigator()
            let vc = ResultController(viewModel: vm, navigator: nav)
            viewController?.navigationController?.navigationBar.isHidden = true
            viewController?.navigationController?.pushViewController(vc, animated: true)
        }
    }

    deinit {
        print("Deinit: " + String(describing: type(of: self)))
    }

}
