//
//  MoreResultController.swift
//  baseapp
//
//  Created Thanh Nguyên Trần on 20/04/2022.
//  Copyright © 2022 Avengers Mobile Team. All rights reserved.
//
//  Template generated by Avengers Mobile Team
//

import UIKit

//                        _oo0oo_
//                       o8888888o
//                       88" . "88
//                       (| -_- |)
//                       0\  =  /0
//                     ___/`---'\___
//                   .' \|     |// '.
//                  / \|||  :  |||// \
//                 / _||||| -:- |||||- \
//                |   | \\  -  /// |   |
//                | \_|  ''\---/''  |_/ |
//                \  .-\__  '-'  ___/-. /
//              ___'. .'  /--.--\  `. .'___
//           ."" '<  `.___\_<|>_/___.' >' "".
//          | | :  `- \`.;`\ _ /`;.`/ - ` : | |
//          \  \ `_.   \_ __\ /__ _/   .-` /  /
//      =====`-.____`.___ \_____/___.-`___.-'=====
//                        `=---='
// Đức phật nơi đây phù hộ code con chạy không Bug. Nam mô a di đà Phật

class MoreResultController: BaseController<MoreResultViewModel, MoreResultNavigator> {


    // MARK: - Properties

    @IBOutlet weak var moreResultTableView: UITableView!
    
    @IBOutlet weak var backBtn: UIButton!
    var dataSource = MoreResultDataSource()
    // MARK: - Life Cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setUpTableView()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

    }


    // MARK: - Binding UI
    override func bindUI() {
        super.bindUI()
        backBtn.reactive.tap.observeNext { [weak self] in
        guard let strongSelf = self else { return }
        strongSelf.navigationController?.popViewController(animated: true)
    }
    }

    //MARK: - Functions
    func doSomeThing() {

    }
    func setUpTableView() {
            self.moreResultTableView.separatorColor = UIColor.clear
            dataSource.itemIdentifyType = viewModel.itemIdentifyType
            dataSource.array = viewModel.moreResulstArray
           dataSource.userImage = self.viewModel.userImage
           dataSource.moreResultDelegate = self
        
           moreResultTableView.delegate = dataSource
           moreResultTableView.dataSource = dataSource
           dataSource.registerCell(forTableView: moreResultTableView)
    }

}

// MARK: - Extension
extension MoreResultController : MoreResultDataSourceDelegate {
    func loadResultVC(itemModelArray: [ItemModel], atIndex: Int) {
        self.navigator?.navigate(to: .results(itemModelArray: itemModelArray, identifyType: self.viewModel.itemIdentifyType, index: atIndex, userImage: self.viewModel.userImage))
    }
}
