//
//  CameraViewModel.swift
//  baseapp
//
//  Created Thanh Nguyên Trần on 14/04/2022.
//  Copyright © 2022 Avengers Mobile Team. All rights reserved.
//
//  Template generated by Avengers Mobile Team
//

import Foundation

//                        _oo0oo_
//                       o8888888o
//                       88" . "88
//                       (| -_- |)
//                       0\  =  /0
//                     ___/`---'\___
//                   .' \|     |// '.
//                  / \|||  :  |||// \
//                 / _||||| -:- |||||- \
//                |   | \\  -  /// |   |
//                | \_|  ''\---/''  |_/ |
//                \  .-\__  '-'  ___/-. /
//              ___'. .'  /--.--\  `. .'___
//           ."" '<  `.___\_<|>_/___.' >' "".
//          | | :  `- \`.;`\ _ /`;.`/ - ` : | |
//          \  \ `_.   \_ __\ /__ _/   .-` /  /
//      =====`-.____`.___ \_____/___.-`___.-'=====
//                        `=---='
// Đức phật nơi đây phù hộ code con chạy không Bug. Nam mô a di đà Phật

class CameraViewModel: BaseViewModel{
    
    var itemIdentify: HomeItemType = .plant
    var isDone: Observable<Bool> = Observable<Bool>.init(false)
   
    func loadAPI(image : UIImage , type: HomeItemType ,complete: @escaping (([ItemModel]?) -> Void)){
        switch type {
        case .plant:
            RestAPI.shared.getPlantIdentify(image: image) { results in
                if results == nil {
                    complete(nil)
                }
                else {
                    complete(results!)
                }
            }
        case .bug:
            RestAPI.shared.getBugIdentify(image: image) { results in
                if results == nil {
                    complete(nil)
                }
                else {
                    complete(results!)
                }
            }
        }
    }
    deinit {
        print("Deinit: " + String(describing: type(of: self)))
    }

}
