//
//  DetailResultViewModel.swift
//  baseapp
//
//  Created Thanh Nguyên Trần on 20/04/2022.
//  Copyright © 2022 Avengers Mobile Team. All rights reserved.
//
//  Template generated by Avengers Mobile Team
//

import Foundation

//                        _oo0oo_
//                       o8888888o
//                       88" . "88
//                       (| -_- |)
//                       0\  =  /0
//                     ___/`---'\___
//                   .' \|     |// '.
//                  / \|||  :  |||// \
//                 / _||||| -:- |||||- \
//                |   | \\  -  /// |   |
//                | \_|  ''\---/''  |_/ |
//                \  .-\__  '-'  ___/-. /
//              ___'. .'  /--.--\  `. .'___
//           ."" '<  `.___\_<|>_/___.' >' "".
//          | | :  `- \`.;`\ _ /`;.`/ - ` : | |
//          \  \ `_.   \_ __\ /__ _/   .-` /  /
//      =====`-.____`.___ \_____/___.-`___.-'=====
//                        `=---='
// Đức phật nơi đây phù hộ code con chạy không Bug. Nam mô a di đà Phật

class DetailResultViewModel: BaseViewModel{
    var imageArray : [String] = []

    var firstImage : String = ""
    var listItem : HistoryModel!
    var isCollection : Bool = false
    var firstImageCollection : String = ""
//    var favoriteArray = [CollectionModel]()
//    var historyItem: HistoryModel!
    
    func loadData() {
        for imageUrl in listItem.images {
            imageArray.append(imageUrl)
        }
       
        firstImage = imageArray[0]
    }
   
    

    deinit {
        print("Deinit: " + String(describing: type(of: self)))
    }

}
