//
//  DetailResultController.swift
//  baseapp
//
//  Created Thanh Nguyên Trần on 20/04/2022.
//  Copyright © 2022 Avengers Mobile Team. All rights reserved.
//
//  Template generated by Avengers Mobile Team
//

import UIKit
import SDWebImage
import JGProgressHUD
//                        _oo0oo_
//                       o8888888o
//                       88" . "88
//                       (| -_- |)
//                       0\  =  /0
//                     ___/`---'\___
//                   .' \|     |// '.
//                  / \|||  :  |||// \
//                 / _||||| -:- |||||- \
//                |   | \\  -  /// |   |
//                | \_|  ''\---/''  |_/ |
//                \  .-\__  '-'  ___/-. /
//              ___'. .'  /--.--\  `. .'___
//           ."" '<  `.___\_<|>_/___.' >' "".
//          | | :  `- \`.;`\ _ /`;.`/ - ` : | |
//          \  \ `_.   \_ __\ /__ _/   .-` /  /
//      =====`-.____`.___ \_____/___.-`___.-'=====
//                        `=---='
// Đức phật nơi đây phù hộ code con chạy không Bug. Nam mô a di đà Phật

class DetailResultController: BaseController<DetailResultViewModel, DetailResultNavigator> {


    // MARK: - Properties

    @IBOutlet weak var detailResultTableView: UITableView!
    @IBOutlet weak var backBtn: UIButton!
    
    @IBOutlet weak var tableView: UIView!
    @IBOutlet weak var detailResultImage: UIImageView!
    var dataSource = DetailResultDataSource()
    // MARK: - Life Cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        settingTableView()
       
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

    }


    // MARK: - Binding UI
    override func bindUI() {
        super.bindUI()

        backBtn.reactive.tap.observeNext { [weak self] in
            guard let strongSelf = self else { return }
            
            strongSelf.navigationController?.popViewController(animated: true)
        }.dispose(in: bag)
    }

    //MARK: - Functions
    func doSomeThing() {

    }
    func settingTableView() {
        tableView.layer.cornerRadius = 20
        tableView.clipsToBounds = true
        self.detailResultTableView.separatorColor = UIColor.clear
        detailResultTableView.backgroundColor = .clear
        
        viewModel.imageArray.removeFirst()
        dataSource.listImageArray = viewModel.imageArray
        
        dataSource.resultsModel = viewModel.listItem
        print("asd",viewModel.firstImage)
        
        if viewModel.isCollection == true{
            var image = getImageFormDocumentDirectory(lastComponent: viewModel.listItem.image)
            let imageString = (image.absoluteString)
            let imageURL = URL(string: imageString)
            detailResultImage.sd_setImage(with: imageURL, completed: nil)
        }
        else{
            let imageURL = URL(string: viewModel.firstImage)
            detailResultImage.sd_setImage(with: imageURL, completed: nil)
        }
        
        
        dataSource.reslutsDataDelegate = self
        detailResultTableView.delegate = dataSource
        detailResultTableView.dataSource = dataSource
        dataSource.registerCell(forTableView: detailResultTableView)
    }

}

// MARK: - Extension
extension DetailResultController {

}

extension DetailResultController : ResultsDataSourceDelegate {
    func loadWikiCell() {
        self.detailResultTableView.reloadData()
        hud.dismiss(animated: true)
    }
    
    func addLoading() {
        hud.show(in: self.view)
    }
    
    func addCollection() {
        
    }
    func loadMoreResultsVC() {
        
    }
}
